version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: npm run dev
    links:
      - mongo
    ports:
      - "3090:3090"
  mongo:
    image: mongo:3.3
    ports:
      - "27017:27017"
